/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/apartment.glb 
*/
"use client";

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useCustomization } from "../contexts/Customization";

const Model = (props) => {
  const { nodes, materials } = useGLTF("./models/apartment.glb");
  const { wallColor } = useCustomization(); // Get selected wall color from Configurator

  return (
    <group {...props} dispose={null}>
      {/* Walls - Now customizable */}
      <mesh geometry={nodes.wall003.geometry}>
        <meshStandardMaterial color={wallColor.color} />
      </mesh>
      <mesh geometry={nodes.wall004.geometry}>
        <meshStandardMaterial color={wallColor.color} />
      </mesh>
      <mesh geometry={nodes.wall005.geometry}>
        <meshStandardMaterial color={wallColor.color} />
      </mesh>
      <mesh geometry={nodes.wall006.geometry}>
        <meshStandardMaterial color={wallColor.color} />
      </mesh>
      <mesh geometry={nodes.topwall.geometry}>
        <meshStandardMaterial color={wallColor.color} />
      </mesh>

      {/* Other unchanged parts */}
      <mesh
        geometry={nodes.balcony.geometry}
        material={materials["m.ConcreteStone.006"]}
      />
      <mesh
        geometry={nodes.balcony001.geometry}
        material={materials["_Black.005"]}
      />
      <mesh
        geometry={nodes.base.geometry}
        material={materials["m.DarkStoneTile"]}
      />
      <mesh
        geometry={nodes.canopy.geometry}
        material={materials["aluminum2.002"]}
      />
      <mesh
        geometry={nodes.canopy001.geometry}
        material={materials["GDG_Frame_Mtl.003"]}
      />
      <mesh
        geometry={nodes.fence001.geometry}
        material={materials["aluminum2.002"]}
      />
      <mesh
        geometry={nodes.profile001.geometry}
        material={materials["m.DarkShine.002"]}
      />
      <mesh
        geometry={nodes.profile002.geometry}
        material={materials["m.ConcreteStone.006"]}
      />
      <mesh
        geometry={nodes.profile003.geometry}
        material={materials["_Black.005"]}
      />
      <mesh
        geometry={nodes.profile004.geometry}
        material={materials["m.DarkShine.002"]}
      />
      <mesh geometry={nodes.roof.geometry} material={materials["_Black.005"]} />
      <mesh
        geometry={nodes.stair.geometry}
        material={materials["m.DarkStoneTile"]}
      />
      <mesh
        geometry={nodes.stair001.geometry}
        material={materials["StoneTile.003"]}
      />
      <mesh
        geometry={nodes.stair002.geometry}
        material={materials["StoneTile.003"]}
      />
      <mesh
        geometry={nodes.Mesh068.geometry}
        material={materials["aluminum2.002"]}
      />
      <mesh
        geometry={nodes.Mesh068_1.geometry}
        material={materials["glass.005"]}
      />
      <mesh
        geometry={nodes.Mesh078.geometry}
        material={materials["glass.005"]}
      />
      <mesh
        geometry={nodes.Mesh078_1.geometry}
        material={materials["glass.005"]}
      />
      <mesh
        geometry={nodes.Mesh077.geometry}
        material={materials["GDG_Frame_Mtl.003"]}
      />
      <mesh
        geometry={nodes.Mesh077_1.geometry}
        material={materials["GDG_Frame_Mtl.003"]}
      />
      <mesh
        geometry={nodes.Mesh077_2.geometry}
        material={materials["glass.005"]}
      />
      <mesh
        geometry={nodes.Mesh077_3.geometry}
        material={materials["GDG_Frame_Mtl.003"]}
      />
      <mesh
        geometry={nodes.Mesh092.geometry}
        material={materials["GDG_Frame_Mtl.003"]}
      />
      <mesh
        geometry={nodes.Mesh092_1.geometry}
        material={materials["glass.005"]}
      />
      <mesh
        geometry={nodes.Mesh092_2.geometry}
        material={materials["GDG_Frame_Mtl.003"]}
      />
      <mesh
        geometry={nodes.Mesh092_3.geometry}
        material={materials["GDG_Frame_Mtl.003"]}
      />
      <mesh
        geometry={nodes.Mesh091.geometry}
        material={materials["GDG_Frame_Mtl.003"]}
      />
      <mesh
        geometry={nodes.Mesh091_1.geometry}
        material={materials["glass.005"]}
      />
      <mesh
        geometry={nodes.Mesh091_2.geometry}
        material={materials["GDG_Frame_Mtl.003"]}
      />
      <mesh
        geometry={nodes.Mesh091_3.geometry}
        material={materials["GDG_Frame_Mtl.003"]}
      />
      <mesh
        geometry={nodes.Mesh060.geometry}
        material={materials["_Black.005"]}
      />
      <mesh
        geometry={nodes.Mesh060_1.geometry}
        material={materials["_White.003"]}
      />
      <mesh
        geometry={nodes.Mesh079.geometry}
        material={materials["aluminum2.002"]}
      />
      <mesh
        geometry={nodes.Mesh079_1.geometry}
        material={materials["aluminum2.002"]}
      />
      <mesh
        geometry={nodes.Mesh079_2.geometry}
        material={materials["aluminum2.002"]}
      />
      <mesh
        geometry={nodes.Mesh079_3.geometry}
        material={materials["aluminum2.002"]}
      />
      <mesh
        geometry={nodes.Mesh079_4.geometry}
        material={materials["aluminum2.002"]}
      />
    </group>
  );
};

useGLTF.preload("/models/apartment.glb");

export default Model;
