import "./globals.css";
import Loader from "./components/Loader";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Loader gifSrc="/models/kikos.gif" /> {/* Use the correct path */}
        {children}
      </body>
    </html>
  );
}
